import {StyleSheet} from 'react-native';
import {colors} from './colors';

export const typography = StyleSheet.create({
  Heading: {
    color: colors.pureWhite,
    fontFamily: 'Syne',
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: 0.36,
  },
  Heading1: {
    color: colors.pureWhite,
    fontFamily: 'Syne',
    fontSize: 20,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  Heading2: {
    color: colors.pureWhite,
    fontFamily: 'DMSans',
    fontSize: 36,
    fontWeight: '700',
    letterSpacing: 0.54,
  },
  Heading3: {
    color: colors.goldenRod,
    fontFamily: 'DMSans',
    letterSpacing: 0.21,
  },
  Heading4: {
    color: colors.pureWhite,
    fontFamily: 'DMSans',
    fontSize: 24,
    fontWeight: '500',
    letterSpacing: 0.36,
  },
  Heading5: {
    color: colors.pureWhite,
    fontFamily: 'DMSans',
    fontSize: 16,
    fontWeight: '500',
    letterSpacing: 0.24,
  },
  Heading6: {
    color: colors.pureWhite,
    fontFamily: 'DMSans',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.24,
  },
  Heading7: {
    color: colors.softLavender,
    fontFamily: 'DMSans',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  Heading8: {
    color: colors.goldenRod,
    fontFamily: 'Syne',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.24,
  },
  Heading9: {
    color: colors.softLavender,
    fontFamily: 'Syne',
    fontSize: 13,
    letterSpacing: 0.65,
  },
  Heading10: {
    color: colors.pureWhite,
    fontFamily: 'DMSans',
    fontSize: 15,
    fontWeight: '500',
    letterSpacing: 0.225,
  },
  Heading11: {
    color: colors.pureWhite,
    fontFamily: 'DMSans',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.225,
  },
  Heading12: {
    color: colors.pureWhite,
    fontFamily: 'Poppins',
    fontSize: 10,
    fontWeight: '500',
    letterSpacing: 0.75,
  },
  Heading13: {
    color: colors.pureWhite,
    fontFamily: 'Century-Gothic',
    fontSize: 64,
    fontWeight: '700',
    letterSpacing: 0.96,
  },
  Heading14: {
    color: colors.pureWhite,
    fontFamily: 'DMSans',
    fontSize: 26,
    letterSpacing: 0.39,
  },
  Heading15: {
    color: colors.pureWhite,
    fontFamily: 'DMSans',
    fontSize: 4,
    letterSpacing: 0.06,
  },
  Heading16: {
    color: colors.pureWhite,
    fontFamily: 'DMSans',
    fontSize: 16,
    letterSpacing: 0.24,
  },
  Heading17: {
    color: colors.pureWhite,
    fontFamily: 'DMSans',
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: 0.2,
  },
  Heading18: {
    color: colors.goldenRod,
    fontFamily: 'DMSans',
    fontSize: 20,
    fontWeight: '500',
    letterSpacing: 0.3,
  },
  Heading19: {
    color: colors.pureWhite,
    fontFamily: 'Poppins',
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 0.18,
  },
  Heading20: {
    color: colors.pureWhite,
    fontFamily: 'DMSans',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.27,
  },
  Heading21: {
    color: colors.transparentWhite,
    fontFamily: 'DMSans',
    fontSize: 10,
    letterSpacing: 1.1,
  },
  Heading22: {
    color: colors.pureWhite,
    fontFamily: 'DMSans',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.15,
  },
});
